[package]
name = "analog-capture"
version = "0.1.0"
edition = "2021"

[dependencies]
analog-waveform = { path = "../../libs/analog-waveform" }
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "iderm-plugins:analog-capture"
target = { world = "view-plugin", path = "wit/deps/iderm-plugin/iderm-plugin.wit" }

[package.metadata.component.dependencies]
