[package]
name = "example-view-vcd-capture"
version = "0.1.0"
edition = "2021"

[dependencies]
vcd-parser = { path = "../../libs/vcd-parser" }
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "iderm-examples:example-view-vcd-capture"
target = { world = "view-plugin", path = "wit/deps/iderm-plugin/iderm-plugin.wit" }

[package.metadata.component.dependencies]
