#[allow(warnings)]
mod bindings;

use bindings::exports::iderm::plugin::view_provider::Guest;
use bindings::iderm::plugin::types::ProjectInfo;
use bindings::iderm::plugin::view::{
    AxisScale, Band, ChartMarker, ChartPoint, ChartSeries, Colormap, ComposedView, CursorPosition,
    DiagramEdge, DiagramNode, HeatmapCells, HeatmapScalarCells, HeatmapView, NodeAnchor, NodeShape, SeriesRole,
    TableCell, TableView, ViewPrimitive, XyChartView,
};
use bindings::iderm::plugin::types::Severity;

struct Component;

const POINT_COUNT: usize = 60;
const FREQ_MIN_MHZ: f64 = 30.0;
const FREQ_MAX_MHZ: f64 = 1000.0;

/// synthetic 30 MHz-1 GHz EMC emissions sweep -- self-contained, no
/// external fixture file, same "no external data dependency" simplicity
/// as `example-doctor-rule`'s `.gitignore` check. Deterministic (no
/// `rand` dependency): a log-rising base trend plus a small sinusoidal
/// ripple, so it looks like a real noisy measurement without needing an
/// RNG crate in a WASM guest.
///
/// `phase` drifts the ripple over successive live-refresh ticks (see
/// `LIVE_TICK_COMMAND` below) -- this plugin is otherwise static/
/// synthetic and had nothing that actually changed between frames, so
/// there was no real way to verify `idermviz`'s live-mode redraw (axis
/// rescaling, tick repositioning) against genuinely moving data rather
/// than just the tick plumbing firing on schedule.
fn dataset(phase: f64) -> Vec<(f64, f64)> {
    let log_min = FREQ_MIN_MHZ.log10();
    let log_max = FREQ_MAX_MHZ.log10();
    (0..POINT_COUNT)
        .map(|i| {
            let t = i as f64 / (POINT_COUNT - 1) as f64;
            let freq_mhz = 10f64.powf(log_min + t * (log_max - log_min));
            let base = 15.0 + 45.0 * t;
            let ripple =
                6.0 * (i as f64 * 0.7 + phase).sin() + 3.0 * (i as f64 * 1.9 + phase * 1.3).cos();
            let level = (base + ripple).max(5.0);
            (freq_mhz, level)
        })
        .collect()
}

/// CISPR 32 Class B-style radiated emission limit, same two-tier shape
/// already used in this project's own EMC concept mockups (30-230 MHz:
/// 40 dBuV/m, 230 MHz-1 GHz: 47 dBuV/m) -- reused for internal
/// consistency with the target this example was built against, not
/// independently invented.
fn limit_at(freq_mhz: f64) -> f64 {
    if freq_mhz < 230.0 { 40.0 } else { 47.0 }
}

fn nearest_index(data: &[(f64, f64)], freq_mhz: f64) -> usize {
    data.iter()
        .enumerate()
        .min_by(|(_, a), (_, b)| (a.0 - freq_mhz).abs().total_cmp(&(b.0 - freq_mhz).abs()))
        .map(|(i, _)| i)
        .unwrap_or(0)
}

/// reserved live-refresh token -- see `app.rs`'s `LIVE_TICK_COMMAND` on
/// the Core side. Not part of the WIT contract by design (Idermviz.md:
/// "a plugin becomes live-capable purely by choosing to recognize one
/// more string in its own `handle-command` vocabulary") -- a plugin
/// author has to know this string from the docs, the same way they'd
/// know any other reserved convention that isn't type-checked.
const LIVE_TICK_COMMAND: &str = "\0tick";

/// which primitive `render_primitives` returns -- curve+table is the
/// original example, `Heatmap`/`Composed` were added alongside their
/// respective view-primitive variants. A plain `u8` (not a real Rust
/// enum) since it round-trips through `encode_state`'s byte vector
/// directly; `TryFrom<u8>` keeps decoding honest about what values are
/// actually valid not silently wrapping/clamping.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Mode {
    Curve,
    Heatmap,
    Composed,
}

impl TryFrom<u8> for Mode {
    type Error = String;
    fn try_from(v: u8) -> Result<Self, String> {
        match v {
            0 => Ok(Mode::Curve),
            1 => Ok(Mode::Heatmap),
            2 => Ok(Mode::Composed),
            other => Err(format!("corrupt view-state: unknown mode byte {other}")),
        }
    }
}

/// opaque view-state per the WIT contract: cursor frequency + ripple
/// phase (two little-endian f64s) plus a trailing mode byte (17 bytes
/// total) -- the dataset itself is otherwise regenerated by the pure
/// `dataset()`/`field_values()` functions not persisted, so
/// there's nothing else that needs to round-trip through `state`.
fn encode_state(cursor_freq_mhz: f64, phase: f64, mode: Mode) -> Vec<u8> {
    let mut bytes = cursor_freq_mhz.to_le_bytes().to_vec();
    bytes.extend_from_slice(&phase.to_le_bytes());
    bytes.push(mode as u8);
    bytes
}

fn decode_state(state: &[u8]) -> Result<(f64, f64, Mode), String> {
    let bytes: [u8; 17] = state
        .try_into()
        .map_err(|_| format!("corrupt view-state: expected 17 bytes, got {}", state.len()))?;
    let cursor_freq_mhz = f64::from_le_bytes(bytes[0..8].try_into().unwrap());
    let phase = f64::from_le_bytes(bytes[8..16].try_into().unwrap());
    let mode = Mode::try_from(bytes[16])?;
    Ok((cursor_freq_mhz, phase, mode))
}

const FIELD_WIDTH: u32 = 24;
const FIELD_HEIGHT: u32 = 12;

/// synthetic spatial field-strength grid -- a falloff from a fixed "hot
/// spot" corner plus the same ripple math `dataset()` uses, just applied
/// over 2D space instead of frequency. Targets `Idermviz.md`'s own
/// reference case for this primitive ("EMC heatmap"), same EMC theme
/// this plugin already carries via its xy-chart/table.
fn field_values(phase: f64) -> Vec<f64> {
    (0..FIELD_HEIGHT)
        .flat_map(|y| {
            (0..FIELD_WIDTH).map(move |x| {
                let dx = x as f64 - 4.0;
                let dy = y as f64 - 3.0;
                let dist = (dx * dx + dy * dy).sqrt();
                let ripple = 3.0 * (x as f64 * 0.5 + phase).sin();
                (60.0 - dist * 2.2 + ripple).max(5.0)
            })
        })
        .collect()
}

/// shared by `heatmap_primitive` (bare field) and `composed_primitive`
/// (field + overlay) — same underlying grid either way.
fn build_heatmap(phase: f64) -> HeatmapView {
    let values = field_values(phase);
    let value_min = values.iter().cloned().fold(f64::INFINITY, f64::min);
    let value_max = values.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    HeatmapView {
        width: FIELD_WIDTH,
        height: FIELD_HEIGHT,
        cells: HeatmapCells::Scalar(HeatmapScalarCells {
            values,
            value_min,
            value_max,
            colormap: Colormap::PerceptuallyUniform,
        }),
    }
}

fn heatmap_primitive(phase: f64) -> ViewPrimitive {
    ViewPrimitive::Heatmap(build_heatmap(phase))
}

/// composed view (ADR-015): the same field-strength heatmap with a
/// synthetic board outline and a warning-status hot-spot marker overlaid
/// -- the real target this primitive was designed for (a PCB/component
/// outline traced over an EMC field map), plus one highlighted edge so
/// the example exercises `overlay-edges` too, not just node placement.
fn composed_primitive(phase: f64) -> ViewPrimitive {
    let heatmap = build_heatmap(phase);
    let board = DiagramNode {
        id: "board".to_string(),
        label: "Board".to_string(),
        shape: NodeShape::Rectangle,
        status: None,
        anchor: Some(NodeAnchor { x: 6.0, y: 3.0, width: 12.0, height: 6.0 }),
    };
    let hotspot = DiagramNode {
        id: "hotspot".to_string(),
        label: "Hot".to_string(),
        shape: NodeShape::RoundedRectangle,
        status: Some(Severity::Warning),
        anchor: Some(NodeAnchor { x: 1.0, y: 1.0, width: 4.0, height: 3.0 }),
    };
    ViewPrimitive::Composed(ComposedView {
        heatmap,
        overlay_nodes: vec![board, hotspot],
        overlay_edges: vec![DiagramEdge {
            from_id: "hotspot".to_string(),
            to_id: "board".to_string(),
            label: None,
            highlighted: true,
        }],
    })
}

/// forgiving parse for the `cursor` command's argument. The usage
/// message shows `<freq_mhz>` as placeholder notation (the way a man
/// page shows `<file>` to mean "put a filename here"), but that's a
/// reasonable thing to type literally if you're not steeped in CLI
/// convention -- so angle brackets and a trailing `mhz`/`_mhz` unit
/// suffix (case-insensitive) are stripped before parsing, rather than
/// rejecting `cursor <500.55_mhz>` as an error to correct against a hint
/// that itself suggested typing that.
fn parse_freq_mhz(arg: &str) -> Result<f64, String> {
    let mut s = arg.trim();
    if s.len() >= 2 && s.starts_with('<') && s.ends_with('>') {
        s = &s[1..s.len() - 1];
    }
    let lower = s.to_ascii_lowercase();
    let stripped_len = lower
        .strip_suffix("_mhz")
        .or_else(|| lower.strip_suffix("mhz"))
        .map(str::len);
    let s = match stripped_len {
        Some(len) => &s[..len],
        None => s,
    };
    s.trim()
        .parse::<f64>()
        .map_err(|_| format!("cursor: {arg:?} is not a number — try \"cursor 500\" (no brackets/units needed)"))
}

/// chart+table in `Curve` mode, one primitive alone in `Heatmap`/
/// `Composed` mode -- never combined, since `ui.rs`'s primary-slot
/// precedence would just make the higher one win anyway
/// (`Composed > Heatmap > XyChart`) if more than one were returned
/// together. The table stays curve-mode-only: nothing in the field/
/// composed views has an equivalent per-point margin table yet.
fn render_primitives(cursor_freq_mhz: f64, phase: f64, mode: Mode) -> Vec<ViewPrimitive> {
    match mode {
        Mode::Heatmap => return vec![heatmap_primitive(phase)],
        Mode::Composed => return vec![composed_primitive(phase)],
        Mode::Curve => {}
    }
    let data = dataset(phase);
    let cursor_idx = nearest_index(&data, cursor_freq_mhz);
    let (cursor_x, cursor_y) = data[cursor_idx];
    let cursor_limit = limit_at(cursor_x);
    let cursor_margin = cursor_limit - cursor_y;

    let measured = ChartSeries {
        name: "E-field".to_string(),
        role: SeriesRole::Measured,
        points: data.iter().map(|&(x, y)| ChartPoint { x, y }).collect(),
    };
    let limit = ChartSeries {
        name: "Limit".to_string(),
        role: SeriesRole::Limit,
        points: data.iter().map(|&(x, _)| ChartPoint { x, y: limit_at(x) }).collect(),
    };

    let marker_status = if cursor_margin < 0.0 {
        Severity::Error
    } else if cursor_margin < 6.0 {
        Severity::Warning
    } else {
        Severity::Info
    };

    // measurement-uncertainty band (ADR-017) -- a real CISPR-report
    // concept, not an invented demo value: the measured trace is never
    // exact, it's reported alongside an uncertainty figure. `status:
    // none` since this isn't itself a pass/fail signal, just an
    // interval around the measurement.
    const UNCERTAINTY_DB: f64 = 3.0;
    let uncertainty_band = Band {
        upper: data.iter().map(|&(x, y)| ChartPoint { x, y: y + UNCERTAINTY_DB }).collect(),
        lower: data.iter().map(|&(x, y)| ChartPoint { x, y: (y - UNCERTAINTY_DB).max(0.0) }).collect(),
        label: format!("±{UNCERTAINTY_DB:.0} dB uncertainty"),
        status: None,
    };

    let chart = ViewPrimitive::XyChart(XyChartView {
        series: vec![measured, limit],
        x_scale: AxisScale::Log,
        y_scale: AxisScale::Linear,
        markers: vec![ChartMarker { x: cursor_x, y: cursor_y, status: marker_status }],
        cursor: Some(CursorPosition { x: cursor_x, y: cursor_y }),
        bands: vec![uncertainty_band],
    });

    let peak = data.iter().map(|&(_, y)| y).fold(f64::NEG_INFINITY, f64::max);
    let avg = data.iter().map(|&(_, y)| y).sum::<f64>() / data.len() as f64;
    let rms = (data.iter().map(|&(_, y)| y * y).sum::<f64>() / data.len() as f64).sqrt();

    let margin_status = Some(marker_status);
    let table = ViewPrimitive::Table(TableView {
        headers: vec!["Metric".to_string(), "Value (dBuV/m)".to_string()],
        rows: vec![
            vec![
                TableCell { text: "Peak".to_string(), status: None },
                TableCell { text: format!("{peak:.1}"), status: None },
            ],
            vec![
                TableCell { text: "Avg (30M-1G)".to_string(), status: None },
                TableCell { text: format!("{avg:.1}"), status: None },
            ],
            vec![
                TableCell { text: "RMS".to_string(), status: None },
                TableCell { text: format!("{rms:.1}"), status: None },
            ],
            vec![
                TableCell { text: format!("Margin @ {cursor_x:.1} MHz"), status: margin_status },
                TableCell { text: format!("{cursor_margin:+.1}"), status: margin_status },
            ],
        ],
    });

    vec![chart, table]
}

impl Guest for Component {
    fn view_id() -> String {
        "emc".to_string()
    }

    /// deliberately calls back into `host::log` to prove the host import
    /// crosses the WASM sandbox boundary from inside a real compiled
    /// `view-provider` component, not just that init's own argument/
    /// return types serialize correctly — same round-trip proof
    /// `example-doctor-rule` already established for `doctor-rule` via
    /// `host::read_file`.
    fn init(project: ProjectInfo) -> Result<Vec<u8>, String> {
        bindings::iderm::plugin::host::log(&format!(
            "emc: init for project at {}",
            project.root_path
        ));
        // default cursor to the worst-margin point -- more useful than an
        // arbitrary fixed frequency, and cheap since the dataset is
        // already a pure function of nothing but point index.
        let data = dataset(0.0);
        let worst = data
            .iter()
            .min_by(|a, b| {
                (limit_at(a.0) - a.1).total_cmp(&(limit_at(b.0) - b.1))
            })
            .copied()
            .unwrap_or((FREQ_MIN_MHZ, 0.0));
        Ok(encode_state(worst.0, 0.0, Mode::Curve))
    }

    fn render(state: Vec<u8>) -> Result<Vec<ViewPrimitive>, String> {
        let (cursor_freq_mhz, phase, mode) = decode_state(&state)?;
        Ok(render_primitives(cursor_freq_mhz, phase, mode))
    }

    /// vocabulary: `cursor <freq_mhz>` (snapped to the nearest real data
    /// point -- not the mockup's full flag language, that's a
    /// plugin-author extension exercise, not something this example
    /// needs to prove the `handle-command` round-trip works), `heatmap`
    /// and `composed` (each toggles curve mode against itself, see
    /// `render_primitives`), plus the reserved live-refresh token,
    /// opted into here specifically so `idermviz`'s live-mode redraw
    /// has real moving data to prove itself against instead of only
    /// the tick-scheduling plumbing.
    fn handle_command(state: Vec<u8>, command: String) -> Result<(Vec<u8>, Vec<ViewPrimitive>), String> {
        let (cursor_freq_mhz, phase, mode) = decode_state(&state)?;
        let mut parts = command.split_whitespace();
        match parts.next() {
            Some("cursor") => {
                let arg = parts
                    .next()
                    .ok_or_else(|| "usage: cursor 500 (plain number, MHz)".to_string())?;
                let requested = parse_freq_mhz(arg)?;
                let data = dataset(phase);
                let idx = nearest_index(&data, requested);
                let snapped_freq = data[idx].0;
                let new_state = encode_state(snapped_freq, phase, mode);
                let primitives = render_primitives(snapped_freq, phase, mode);
                Ok((new_state, primitives))
            }
            Some("heatmap") => {
                let toggled = if mode == Mode::Heatmap { Mode::Curve } else { Mode::Heatmap };
                let new_state = encode_state(cursor_freq_mhz, phase, toggled);
                let primitives = render_primitives(cursor_freq_mhz, phase, toggled);
                Ok((new_state, primitives))
            }
            Some("composed") => {
                let toggled = if mode == Mode::Composed { Mode::Curve } else { Mode::Composed };
                let new_state = encode_state(cursor_freq_mhz, phase, toggled);
                let primitives = render_primitives(cursor_freq_mhz, phase, toggled);
                Ok((new_state, primitives))
            }
            Some(token) if token == LIVE_TICK_COMMAND => {
                let next_phase = phase + 0.15;
                let new_state = encode_state(cursor_freq_mhz, next_phase, mode);
                let primitives = render_primitives(cursor_freq_mhz, next_phase, mode);
                Ok((new_state, primitives))
            }
            Some(other) => Err(format!(
                "unknown command: {other:?} (try \"cursor 500\", \"heatmap\", or \"composed\")"
            )),
            None => Err("empty command".to_string()),
        }
    }
}

bindings::export!(Component with_types_in bindings);
